name: Handle Python Backend

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to add'
        required: true
        type: string
      timestamp:
        description: 'Timestamp for the message'
        required: true
        type: string

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Run the Python script to update data.json
      - name: Run Python script
        run: |
          python datasubmit.py "${{ github.event.inputs.message }}" "${{ github.event.inputs.timestamp }}"
      
      # Commit and push updated data.json back to the repository
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data.json
          git commit -m 'Update data.json with new message'
          git push
